-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMxG+p57WZ3v1kyVs
Wnu2HAUgDtLaZQiOUpQ8H1HsOd6gCgYIKoZIzj0DAQehRANCAATo1dIJ1RCE1S/2
0Sdvhpz6+KhXqtLn2oG/inlyhMfg/XtJvxAwtWbxksxoMlMuyNTwFwp8mlWh+Ipk
OTqtoRVq
-----END PRIVATE KEY-----